### ISSUE TITLE
Virtual environment activation on Docker

### ISSUE THREAD

**Issue by brunosphair** [tiagokretzerwalter/wedding-planner#11]
I don't know if I am doing it at the proper place, but... I was reading about virtual environment activation inside the Docker and apparently this is exactly what the command below does. 

https://github.com/tiagokretzerwalter/wedding-planner/blob/ef3defd2e6bcb8012f5b9fcf43a0cca986cfaca7/Dockerfile#L21

But you can see in the Dockerfile, inside the "RUN", we repeat the path "/py/bin/pip" before every command we pass to python to specify the venv folder. This is not necessarily a problem, because we don't have a lot of runs, but if the list increase, increases the chance that we forget to put the path before the command. To solve this I suggest to move this PATH changing in Dockerfile after the virtual environment creation and before the pip upgrade, so we can install requirements and call other python commands using only "pip".

What do you think?

**Comment by tiagokretzerwalter** [comment]
Well put, however I am not sure if the first command would be executed. You might as well try it and check if it works :).

**Comment by gabrielpalves** [comment]
Great idea! It makes sense to automate this since we use `/py/bin` more than once already.

**Comment by brunosphair** [comment]
The change was proposed with the PR #15
